# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 023f450256133d014253f070979443981be0cddd789d1208824d4a2d6bdff5a2d1fc63b68244a475fc15bacba65d357183c023a6788309d84738fc470c5a69d0

test:
  secret_key_base: 8574e1e1f4a9cc0879bf6c8b27f19f8639b89e2b648e9edaae8a1bff58eb74d68b425689f883d9a37f14764374d3b507a6c9653cf0f264d1e3d13203eae0b547

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
